kind: Secret
apiVersion: v1
metadata:
  namespace: {{ .Values.namespace }}
  name: github
data:
  api-token: {{ .Values.github.api-token | b64enc }}

---

kind: Secret
apiVersion: v1
metadata:
  namespace: {{ .Values.namespace }}
  name: slack
data:
  api-token: {{ .Values.slack.api-token | b64enc }}

---

kind: Secret
apiVersion: v1
metadata:
  namespace: {{ .Values.namespace }}
  name: database
data:
  jdbc-url: {{ .Values.database.jdbc-url | b64enc }}
  username: {{ .Values.database.username | b64enc }}
  password: {{ .Values.database.password | b64enc }}
