kind: ServiceAccount
apiVersion: v1
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ template "fullname" . }}-account
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name }}
